#开发环境配置
spring:
  application:
    name: tpuser
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: localhost
        port: 8081
  #配置数据库连接
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/Ticket?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
