server:
  port: 8088
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        ip: localhost
        port: 8088
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: tp-order
          uri: lb://tp-order/ #lb标识使用负载均衡，后面是该应用在Nacos中的地址标识（服务名称）
          predicates:
            - Path=/tp_order/** #拦截有该前缀的请求并把它交给对应的应用

        - id: tp-user
          uri: lb://tp-user/ #lb标识使用负载均衡，后面是该应用在Nacos中的地址标识（服务名称）
          predicates:
            - Path=/tp_user/** #拦截有该前缀的请求并把它交给对应的应用
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ticket?characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      database: 0
      timeout: 3000
      host: localhost
      port: 6379

