server:
  port: 8081
spring:
  application:
    name: common
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段