server:
  port: 8081
spring:
  application:
    name: common
  data:
    redis:
      database: 0
      host: 8.134.129.167
      port: 6379
      password: 542245
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.schurfroggy.cn:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段